"""
LLM-callable tools for managing experience data.
"""


def persist_experience(text_chunk: str, experience_id: str) -> None:
    """
    Parse a natural-language or markdown text chunk describing an experience
    item and write it to the file DB at the path for the given experience_id.

    Called by the LLM agent when the user provides details about an experience,
    job, or skill entry. The text_chunk may be the raw content of a user message
    or a structured markdown block generated by the LLM.

    Args:
        text_chunk: Markdown or prose describing the experience item.
        experience_id: UUID of the experience/job/skill record in the DB.
    """
    raise NotImplementedError


def update_experience_overview(username: str, text_chunk: str) -> None:
    """
    Rewrite the user's profile overview (user_info.md) based on a new text chunk.

    Called by the LLM agent after the user updates their general profile summary,
    objective, or high-level background description.

    Args:
        username: The user whose user_info.md to update.
        text_chunk: Updated profile overview text in markdown.
    """
    raise NotImplementedError


def search_experience(username: str, application_id: str) -> None:
    """
    LLM call that identifies which of the user's experience entries are most
    relevant to a given job application and persists the results.

    Process:
        1. Loads all experience markdown files for the user from the file DB.
        2. Loads job_info.md and company_research.md for the application.
        3. Calls the LLM to rank/select the most relevant experience IDs.
        4. Writes the selected IDs to:
               file_db/{username}/applications/{application_id}/relevant_experience.md

    Known scaling concern: for users with many experience entries this will
    eventually approach context window limits. Future versions should chunk
    or embed experience entries.

    Args:
        username: The user whose experience library to search.
        application_id: UUID of the application being tailored.
    """
    raise NotImplementedError
